---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: kuma
  namespace: kuma
spec:
  module: http_2xx
  prober:
    url: blackbox-exporter.blackbox-exporter.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - "https://status.${SECRET_DEFAULT_DOMAIN}"
