---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vm
  namespace: flux-system
spec:
  releaseName: vm
  chartRef:
    kind: OCIRepository
    name: victoria-metrics-k8s-stack
    namespace: flux-system
  targetNamespace: victoriametrics
  interval: 10m
  timeout: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: VMAlertmanager
              name: vm-victoria-metrics-k8s-stack
            patch: |-
              - op: remove
                path: /spec/securityContext
  values:
    victoria-metrics-operator:
      operator:
        enable_converter_ownership: true
      podSecurityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL

    vmsingle:
      spec:
        retentionPeriod: "14d"
        useStrictSecurity: true
        storage:
          storageClassName: ${STORAGE_READWRITEONCE}
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
          limits:
            memory: 2Gi
        extraArgs:
          memory.allowedPercent: "80"

    vmagent:
      spec:
        scrapeInterval: 60s
        useStrictSecurity: true
        externalLabels:
          cluster: ${CLUSTER_NAME}
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            memory: 512Mi

    vmalert:
      spec:
        evaluationInterval: 60s
        useStrictSecurity: true
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            memory: 256Mi

    syncJob:
      enabled: false

    alertmanager:
      enabled: true
      spec:
        securityContext: null
        retention: 120h
        useStrictSecurity: true
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            memory: 256Mi
        storage:
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
              storageClassName: ${STORAGE_READWRITEONCE}

    grafana:
      enabled: false
    prometheus-node-exporter:
      enabled: false

    kubeProxy:
      enabled: false

    defaultDashboardsEnabled: false
