---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../cilium/ks.yaml
  - ../cert-manager/ks.yaml
  - ../flux-operator/ks.yaml
  - ../kyverno/app-ks.yaml
  - ../kyverno/policies-ks.yaml
  - ../metrics-server/ks.yaml
  - ../node-exporter/ks.yaml
  - ../openebs/ks.yaml
  - ../prometheus-operator-crds/ks.yaml
  - ../cloudnative-pg/operator-ks.yaml
  - ../cloudnative-pg/plugin-ks.yaml
  - ../volsync/ks.yaml
