---
apiVersion: v1
kind: Secret
metadata:
  name: forgejo-postgres
  namespace: forgejo
stringData:
  s3-access-key: "${SECRET_S3_VOLSYNC_ACCESS_KEYS}"
  s3-secret-key: "${SECRET_S3_VOLSYNC_SECRET_KEYS}"
  region: "eu-stockholm-1"
