apiVersion: ENC[AES256_GCM,data:p+k=,iv:juiSg3sT5ytGG/mloQmeyyfsGhR09Vn2XrJ2i/l8rR0=,tag:rCnaue+dvU1bBwg2+XQwMw==,type:str]
kind: ENC[AES256_GCM,data:jVKNybrM,iv:G6aNqaSKaG1cozduFTGMnpYBhMosU6gibsD/hzwTjSA=,tag:wY0xProQO2Pa+EJG21mvfg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:DjnXoYK6+qCJmmZthfM=,iv:0ICVUHn3VWQLSPzhm2uIdHdwRaTBJTN6k2lOv0HT9Lk=,tag:IipGNtFWaLdAl1JA5Lawgg==,type:str]
    namespace: ENC[AES256_GCM,data:jzLnoABgKQ==,iv:Dg5+vrVAe25ak0TfAYoT6taR+fXxqCp3CmsGL6csVJE=,tag:swQJWxpQyQkGAN003qI4eg==,type:str]
type: ENC[AES256_GCM,data:qt17N4TT,iv:aj/lAG2pr972wzCcLtVUnTLcRMPYvvufuM1TcluFAL8=,tag:iXyzEXsMuJoyRV5l2bNWpQ==,type:str]
stringData:
    username: ENC[AES256_GCM,data:RC7l6w==,iv:hY9m500jJ5c2xE1P1W4c+S10blY4BMz69UENHB4jlhk=,tag:t5IjvYKcNioLaEFLIeCB9A==,type:str]
    password: ENC[AES256_GCM,data:eMV9o6vS/2At0xbZ+XKCQ6Ip2Ojzu7yBjIruzhJjr6WD9z0IlOP4Pr+EoXmqG8JIeGQjROt/lhnYvXm40+z65Q==,iv:mrOkkrzQcufooKu4WMb7QDMIpxSX0CLN9cavaYCgrGA=,tag:/NzHPdwdx6Vyh4FOIuq3cw==,type:str]
    email: ENC[AES256_GCM,data:yGPSeSXogJh8QMwDwmf1Nxg7VeJV,iv:iZIS0nmwc5dNhu4PYFzQ3YKSWyYGYEYGXv+Q3EFJVts=,tag:zTDaxD4pnPUkkM5U4KjXlg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzaHRhRUpIaEZqR2laK0Ur
            aC9lKzNnaEZ2cmtsN2l2NnBwNU9nRWowNFhrCmI1a2FnejVDTHZlb0xXUHBDSHhN
            VmJxT2RBSTlDZzFJV3lvY2lSRlRBVGcKLS0tIFovY01mSFY4Uk43OFp5b0ZNdTZH
            eGNVajNKaU1iUllBaUVDbHc3L3ZVdmMK6g15fsf793sXdb2r0LwVrXrEs8FiFurJ
            qxGQbSt+m7xwGvz75YxW4s4ZVWVVX98N00qDq+HbeQEyKExz/kUveQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1luplm36pk0f4j5835tygt6wuqfjqe7ra6u8w0t86xrhhprycgfysjjmgux
    lastmodified: "2026-07-03T12:05:35Z"
    mac: ENC[AES256_GCM,data:8Wy1b5Yv8CTIiTbqyxbJ8A3Nrf+dAGSWx3N0o6LTJU1l1CZf6m1Ct+s1LdPntTa5HyZr0k21bTu3I4HCc/4akVDdzRtq+9K/ihJ+lVadmyLuf0YrVmH7GZTk5Vy6/CxwqiYi8coLytR+pdr18h+ze46Sbz5IsxmfRZWH+Muj/zI=,iv:bKyZzINOy1Gnzc6b1XFzZA++oWh2Rgee1Z11fHwIPTE=,tag:T/DsHTKt0Ou964NcDgY7/A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
