apiVersion: ENC[AES256_GCM,data:EkA=,iv:CbRvRxFZxTR9UcbG4oMrpUhi4Zm/S41buPgLdGwGYgw=,tag:8/I8T3GO/Vkq8SWU+dK/GQ==,type:str]
kind: ENC[AES256_GCM,data:7R9MLnsu,iv:wDvEpC15923w687OAhQXR9/q5cHxIAVJH6VAdTa1GWs=,tag:kTIDu5kZgbW+gbO6DohYOg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3KowdWaAZl242lpzw3k=,iv:009Am54UXe3IaVN9z8RaZN8fjIBMQ2GNT73ZBjtFNKA=,tag:lZsYZdfdt3a0HeRhMy3D2g==,type:str]
    namespace: ENC[AES256_GCM,data:tLGmKLhuXg==,iv:6w490dwbC0IvgH4QyZba23a+Hpm4aDWqN2CQKa3tm3A=,tag:riHjMlhMgV6w6rHR98Bypw==,type:str]
type: ENC[AES256_GCM,data:Uf3gXOy5,iv:PSyx5F905tDLsLjVeyAhmVOMxhEzZSkcnj3u7w3AOUQ=,tag:AXcgHHfnRqOTrRpJQZf1NA==,type:str]
stringData:
    username: ENC[AES256_GCM,data:jwDcphU=,iv:EbBNcVY2xYJ3qcXjwbNfygKPd+fsaEMytd4s+ye7zj0=,tag:3lXHhBYXKep+lt2WY5ZwZQ==,type:str]
    password: ENC[AES256_GCM,data:7HdL2db/68lHQUBQ4+LRnRPxAUbG7wFIej78XBTDfp9NTDjpMldKrNGT9qwBG1n23tOM0uU1TnsiimzkdcONnw==,iv:+ADraGT8PWf8TO1TskCOMJcnozpVvYbfJj69Nv9G8yQ=,tag:e1VukokhIWoPFVfhaxUp0Q==,type:str]
    email: ENC[AES256_GCM,data:Hk5GNcK72VnbtDSA60h8StEm803X,iv:7vTTboKNA7f+Vt7M5he4GwWsdipTN2S3W3rgyjm3qP8=,tag:BHAkXQFHZj4S3T6FTE23tg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWld5OVMrR0pwTUxSZ2o2
            NUFDNEhGYm5RcUJwL2R1T2psMWJmUm0rdGlJCmhBZmEydzVKaU5yS2pNS0ZNbEJh
            eU9meitXa3FMTzJZbGJ2aXlrdmE3RTAKLS0tIGRacU13VFlnQXJvQ3Z0MDBUa01y
            bUlWTURHdURTUVJXK3dWL3JpUDhMbDQKYwPrGUcQ8GmHHOC3pzev7OIIo0YTmkvc
            +KFOeog9Yz5fAQ3chYzHgm/xrZQtBawKDYBtnKz/j28qPbGGk1bS2Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1luplm36pk0f4j5835tygt6wuqfjqe7ra6u8w0t86xrhhprycgfysjjmgux
    lastmodified: "2026-07-03T10:50:55Z"
    mac: ENC[AES256_GCM,data:QGDRI+rXWyaHaeK7YJw/L9cgJ74qAtojE/ju8txZlaQoCzld/LLB1FqXJLSmXIFTeuMn4+oTMotjHLBjOWnwzM1AkxAKj80O5Tetl7B0CwyNKW0G+9az/D1xOovnuLUrh03cS38FFzwH6pYGFTKDRE11+5wMn/Rk92rqYMIK5wU=,iv:BIuh2HsXQWSJeAWqJ3WLOrM6744jZl+Ab8MLXvn+cJA=,tag:Y6/UxI2e/ig026yZTgoshA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
