apiVersion: ENC[AES256_GCM,data:KZc=,iv:So6jA+72X4eoWpbT80JtbfVoZWviA7ZMohwn+dbr/ik=,tag:Qh0WLoV9ZJwTcJKUyYVf2A==,type:str]
kind: ENC[AES256_GCM,data:c3MQmZOJ,iv:S1fb5vDuMI8PyBOM/YpFuGRO8J5WEknYYTWk/L0+dds=,tag:vpqh9WgeuKgLBLFKotOO3w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:e6/Hd6H0J3s8rcwBtzE=,iv:PgBsEjQVSVyYj9HX7zsG8tIl5v7zMZ6Wm/SkzwuimNM=,tag:OxorOFANQJkOdZcz8txXVA==,type:str]
    namespace: ENC[AES256_GCM,data:axzxGfKNoQ==,iv:EVDgpQIXVkK9tnWk+BLhSb4AWXrMuwm0WqJ85vQs7L4=,tag:qz+Md02QUGksz5d7vmv/pg==,type:str]
type: ENC[AES256_GCM,data:le2DH5fm,iv:GC8264XdgpQDrkEAq9PS2DShGLXeOtjOkwuDK/2B8IM=,tag:Xn7qWImNt4gPJvl4/rzEEQ==,type:str]
stringData:
    username: ENC[AES256_GCM,data:gauUkA==,iv:14Bqip9xu64vlSr9X7YfUIOLAbALrnshhkD+6JOREtA=,tag:bRF7J1cGkDDepH9tehCe7Q==,type:str]
    password: ENC[AES256_GCM,data:Zga8pZ0bhHpwxR8bCyaH0SMf1F64oXuO3rzyD8bpZbMUIJIFaNbJPt7HUdfJqIHdQQ50mw3uheg7YrNDvHAhyQ==,iv:DcvrPuJC8dzBUsvI+cWitlDsuoajjT1qFzTjNP+W0RY=,tag:ZMs1o5h7FzzsuMuM+Zrwqw==,type:str]
    email: ENC[AES256_GCM,data:kc8w210Aow6mItIpBG7UoUY=,iv:sQWXcbiP6NRZyCHJU8u7NvF3MqE8G+2Z1FpKS/kHt7k=,tag:a34+IcjntIxNrbwAqOsFXg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRkY3bWxvcEkzeXgvdDhM
            UHdoZzA0aTlhekd4T05pVUtkcFhSZ29KTHpNCkhRakVDY3F3SWdRVlgxdzdYSFNU
            cDdVZzVabnpDc3N0MUs5elV0TVVXdWMKLS0tIGlwSmMyTlN5SkFVUmFpdUpQMHVJ
            OHNiRHdjSkthOGJCYS9YcjdwSmNmMlUKPHeR/QgKRB5ebFIBK9xSBXn3rONcijcN
            zDeI6kK3CXnu8dYC+oqAklBwk1xN/Vqxd/7DIUKfHhhaADse0IjhNQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1luplm36pk0f4j5835tygt6wuqfjqe7ra6u8w0t86xrhhprycgfysjjmgux
    lastmodified: "2026-06-19T12:41:13Z"
    mac: ENC[AES256_GCM,data:QGGiUwoHC+YdzA7nam7wbLjhyfV3qF/wLdN0gGbLyvOv+tOwLQQmWb7nQrs32Mh8fTxyV8Btwp3Wv4TE+m+cgyYxMghcCCAnilm+sll/RWfq+9Si49r32GD27Fknry4qIbXiDdUUtkvH2julZuXiv5vYVWfoV94WaqZbSU6CTGU=,iv:ShhETsdijC2sTiOkKmei1zaaNhcCaDfbqxu35LO6slM=,tag:aaZbt6Jcke0YcICJ2Lgkig==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
