---
apiVersion: v1
kind: Secret
metadata:
  name: forgejo-volsync-secret
  namespace: forgejo
type: Opaque
stringData:
  RESTIC_REPOSITORY: "s3:https://${SECRET_S3_VOLSYNC_HOST}/${SECRET_S3_VOLSYNC_BUCKET}/volsync-${CLUSTER_NAME}/forgejo"
  RESTIC_PASSWORD: "${SECRET_VOLSYNC_RESTIC_PWD}"
  AWS_ACCESS_KEY_ID: "${SECRET_S3_VOLSYNC_ACCESS_KEYS}"
  AWS_SECRET_ACCESS_KEY: "${SECRET_S3_VOLSYNC_SECRET_KEYS}"
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: forgejo-restic
  namespace: forgejo
spec:
  sourcePVC: forgejo
  trigger:
    schedule: "34 * * * *"
  restic:
    copyMethod: Direct
    pruneIntervalDays: 1
    repository: forgejo-volsync-secret
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    retain:
      hourly: 24
      daily: 7
      weekly: 1
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: forgejo-volsync
  namespace: forgejo
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/created-by: volsync
  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
          rules:
            dns:
              - matchPattern: "*"
    - toFQDNs:
        - matchName: ${SECRET_S3_VOLSYNC_HOST}
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
