---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../blackbox-exporter
  - ../cloudflared
  - ../cyberchef
  - ../forgejo
  - ../forgejo-runner
  - ../healthchecks
  - ../it-tools
  - ../kuma
  - ../librespeed
  - ../pocket-id
  - ../prometheus
  - ../tuppr
  - ../wastebin
