---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kuma
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/apps/kuma/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - name: global-settings
        kind: ConfigMap
        optional: false
      - name: global-settings
        kind: Secret
        optional: true
  dependsOn:
    - name: blackbox-exporter
    - name: cilium
    - name: cloudflared
    - name: openebs
    - name: volsync
