---
apiVersion: v1
kind: ConfigMap
metadata:
  name: healthchecks-local-settings
  namespace: healthchecks
data:
  local_settings.py: |-
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
