---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: healthchecks
  namespace: healthchecks
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "${STORAGE_READWRITEONCE}"
  resources:
    requests:
      storage: 2Gi
