apiVersion: v1
kind: Secret
metadata:
    name: healthchecks-secret
    namespace: healthchecks
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:ntCw4AvyXfi6B5KVMkgCybyShHa1RMdha/9Wv/DosS3vcooNy74CJX4BkGtKCzDJ4BvV2pJ5rf9LYHBOxHSOag==,iv:zJ8Nj9+fi0mn5TTqWsi8sIxIShvVf0V838c7WOzzgXc=,tag:YzEbmlj081nbLw7DZI/U8Q==,type:str]
    EMAIL_HOST_USER: ENC[AES256_GCM,data:r9IK6NJrShD6fJZ9TQ==,iv:b5FymA1zoGV0Jy2A0tuMmdN5SF3ROuzmUSWfjRTz6l8=,tag:WSvMYKxo9K/8NYKf0HAxHg==,type:str]
    EMAIL_HOST_PASSWORD: ENC[AES256_GCM,data:GCBoyUpbuISCsnZCyf5nhQ==,iv:9stg9ti6fT5ewtKrmCXfqNXquHe8G2vGpHa2KJtt6Sc=,tag:ojTtohvjdUClmS04yCx3jQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoN0xjcGpaekw3R080ak5z
            TzlOQU9zeUZ4b3VxSkZ0ZS9BUTUzSFNRSFU0CnYyMExrK0ZlSC9jMjR2NEx0cklE
            SUNkL3dGdElZKzBpVHRsTjVJajhSYmMKLS0tIG9NODc0Y3ZmNUhmdlErRzF6a1BM
            ejBobUVEL1BrSHBmem1aNkVubHExUW8KJDHmDztwaxq5fNC2+Hqm3A4pI+6aWGxw
            a3g4Kvf2tkgTA/J3gVIAtNEZ5oddWVp2FkmdXiEb3vkL3GyQtSiHdA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1luplm36pk0f4j5835tygt6wuqfjqe7ra6u8w0t86xrhhprycgfysjjmgux
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T06:35:12Z"
    mac: ENC[AES256_GCM,data:Gk8DibCQvT++h3SiZbwm3VDqicdKAprvwYroDrNsxA8Mp7vVcoy5OlY00pH2RquQSguHq2gk1tF5MXu5LJM2sYCDfhwnOUnI9PEPeeRmIDgopaphxu5z+aWw4izv2lwtKytK+XxpS08iHBXo5aVyIZHhkgUS6X8GqUQdNKC6WbA=,iv:CkPRKTcPZXtwuMMp/lN5ZHht//pcDnFs1jQ170a2jqM=,tag:e+a06hTLnkTmNlGxGPeFxA==,type:str]
    version: 3.13.1
