apiVersion: v1
kind: Secret
metadata:
    name: healthchecks-secret
    namespace: healthchecks
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:ntCw4AvyXfi6B5KVMkgCybyShHa1RMdha/9Wv/DosS3vcooNy74CJX4BkGtKCzDJ4BvV2pJ5rf9LYHBOxHSOag==,iv:zJ8Nj9+fi0mn5TTqWsi8sIxIShvVf0V838c7WOzzgXc=,tag:YzEbmlj081nbLw7DZI/U8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoN0xjcGpaekw3R080ak5z
            TzlOQU9zeUZ4b3VxSkZ0ZS9BUTUzSFNRSFU0CnYyMExrK0ZlSC9jMjR2NEx0cklE
            SUNkL3dGdElZKzBpVHRsTjVJajhSYmMKLS0tIG9NODc0Y3ZmNUhmdlErRzF6a1BM
            ejBobUVEL1BrSHBmem1aNkVubHExUW8KJDHmDztwaxq5fNC2+Hqm3A4pI+6aWGxw
            a3g4Kvf2tkgTA/J3gVIAtNEZ5oddWVp2FkmdXiEb3vkL3GyQtSiHdA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1luplm36pk0f4j5835tygt6wuqfjqe7ra6u8w0t86xrhhprycgfysjjmgux
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-12T21:46:06Z"
    mac: ENC[AES256_GCM,data:pkVUkCdaL9oZE6uRbp5tFszOgfiJdYqoRUTPzZ2Vp8UMe++UuPGyUgCTxkyqh0XO3C+1Hu7ivzzcDyqzFR+epdjWYtHUbpttioyEzt9b2ufBqLsehr0PrBfXOR+tPvFwp73o/xAStZVZ0tjEyz/T+A/merJZw5qlkz9/uukMTa4=,iv:U7dv/KvY51WTOwCLzL4kRUgxRlrjGbCnf1r/GDSgZZc=,tag:vBkIgEC3ah7SErd4ynBiWw==,type:str]
    version: 3.13.1
