---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./deny-workloads-in-reserved-namespaces.yaml
  - ./generate-default-deny-networkpolicy.yaml
