apiVersion: v1
kind: Secret
metadata:
    name: pocket-id-postgres
    namespace: pocket-id
stringData:
    s3-access-key: ENC[AES256_GCM,data:83erfbkBwMyvenTRP5k88Fwx1m5lSFHhf6ih+2c+AH8=,iv:cgg/A8DvIIS7zKcPiZ9i1qTEiYCITolLPQok9pm5/JQ=,tag:vuNM7+AAalq3QQWmS8MhZA==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:4oQYt56Ip2d0pqKfFgiqKwIln9MelxR8QVnpJluxkBA=,iv:nHs5a8yoiysq+N0QIssxNcNkOmA4ybBJmAQx+WMVP9A=,tag:G9SAUc79N23/vqLthmgk9Q==,type:str]
    region: ENC[AES256_GCM,data:k/XbUWj9mh84D0yg9AY=,iv:RQgYtByyRbEcrOh625dOUKj229d9kwR1WMGTIH8tGA8=,tag:pqNJcNoYtqLoj2eEALQHng==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnS2NZQnBoeE5ZSXFMaDE0
            N3JXOXJLOXk2azhYeTcyaWlvbVo2eWptSVM0CnVyYlNmTGRUczVkS2tuV2RGRlVU
            VUtMZjVMY21qUEt0WFhMSXRwUEdRWGsKLS0tICtyb3dMM1JlQ2RDZ0dQSGJQbEJm
            QUhuL2NiUWxJNkZzQTlkbXhxQXdnS0EKAQgdpEgxyDJP1isI+QvMaqM5Y82ktsSs
            pSHkS5NSSvcwByBATyReYo+pgmtAkkSaWuTBfpfejuJ+Bz7kWTnr6w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1luplm36pk0f4j5835tygt6wuqfjqe7ra6u8w0t86xrhhprycgfysjjmgux
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-02T11:22:09Z"
    mac: ENC[AES256_GCM,data:Xo5VjW7SdhEHKKLehDaV6ul00llK6TL/PY1+JLRI4ameucAloXHxqI0YHadDpe9vXBzzyRxB8H51gegoh1TANk1rEkSNtVYT3CYxtizkiocY92bp09EGM2nNncfuEM1M3q7MZT+tfprpoTvCpwPLpKMcqu5mNmpL0z0GudtoLk8=,iv:5nBwgWT3an8ZZ1I+f/zMjNmTP6iHrZQLFI2NVn3wGlY=,tag:UZFh/3mUjVGvhRTOi59gWg==,type:str]
    version: 3.13.1
