apiVersion: v1
kind: Secret
metadata:
    name: pocket-id-secret
    namespace: pocket-id
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:YDK1nM5pXTxkQ2D4waAYjmSfgCJkTYC4KyZT6VK3Lw3CM51TVciNSAXDPaw=,iv:8h52v2f77EqpiZBcXvbpsp4YwJw75D3Boux3H5PxyCE=,tag:3oq1yo10vzCg/GdHTbDhtA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGc2VER0ozTHNSbmE5UWR6
            QUcxQm5DcGFVSy9CZ3BjLzhGeUhFdDZ5SkZRCktUMENCWDQvdGxIalNvL3lvWTh2
            K3UzbWszRFFER2JCSmdUeWxkck5qZzAKLS0tIEFJS3kyTWIraWVOdWVmWGFBVndE
            SlZTaGRZZDZ5SW1WVytNcXBMS0ZkSGsKuaw4TEGaHO8vACINTHYeDXXEipLZECkz
            LnwvCii7d4olUcK59nJ7lxEdBwUwMgjNZYneE2boXgnbNzr1uGYOkQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1luplm36pk0f4j5835tygt6wuqfjqe7ra6u8w0t86xrhhprycgfysjjmgux
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-02T11:22:09Z"
    mac: ENC[AES256_GCM,data:13EhKJzsmdog4wSwhPvYSsVCPsB8hHOWTiCdVsAo185HULGO21n8QMPf62ZUyXXrugku79JFckfx7xyKsfBcSPDT+ToNTVW7A8otwFWpz8kpQqUEbimBPz8owyWCEtg/tXbr4aEslGMr2fYxdGQBIY1KtcFDuDK91EVDD7lRq2Y=,iv:zWOX5x0gsPGntNFP5u4HTSHwrC4P6QR51WROmgoPTAM=,tag:NlAgW0d8Az/18RD8J0l5Tg==,type:str]
    version: 3.13.1
