---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: librespeed
  namespace: librespeed
spec:
  module: http_2xx
  prober:
    url: blackbox-exporter.blackbox-exporter.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - "https://speed.${SECRET_DEFAULT_DOMAIN}"
