apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: forgejo-runner
    namespace: flux-system
spec:
    interval: 30m
    chartRef:
        kind: OCIRepository
        name: forgejo-runner
        namespace: flux-system
    targetNamespace: forgejo-runner
    install:
        createNamespace: false
        remediation:
            retries: 3
    upgrade:
        remediation:
            retries: 3
    driftDetection:
        mode: enabled
    values:
        knownLastVersion: true
        runner:
            config:
                create: false
                file:
                    log:
                        level: info
                    runner:
                        capacity: 1
                        timeout: 3h
                        labels:
                            - docker:docker://docker.io/library/node:20-bookworm
                            - ubuntu-latest:docker://ghcr.io/catthehacker/ubuntu:act-22.04
                            - self-hosted:host
                        envs:
                            A_TEST_ENV_NAME_1: ""
                            A_TEST_ENV_NAME_2: ""
                        env_file: ""
                    cache:
                        enabled: true
                    container:
                        docker_host: tcp://127.0.0.1:2376
                        network: host
                        privileged: false
                        options: -v /certs/client:/certs/client
                        valid_volumes:
                            - /certs/client
                    host:
                        workdir_parent: ""
                    server:
                        connections:
                            forgejo:
                                url: http://forgejo-http.forgejo.svc.cluster.local:3000
                                uuid: ENC[AES256_GCM,data:0af5oDSWNoC4vomWdUY73+TNiPCMsCV+bAnOxYju/LtMZ5Ij,iv:vbgfa2sxQQHpmnd7WV1WIPbknBdWeZnc94vbKQc2zAw=,tag:0nRSBqSSr8Fz6Fww0U99Lw==,type:str]
                                token: ENC[AES256_GCM,data:K0lZuAUdhDZqRBAW/uaPRCGIIwHC+qnc64AnBjdLifQdkwg+bGjwtw==,iv:IDdBkSS/srCECPsyRr6M+2LsJRuYMGyxQK0I5gbfYVY=,tag:IGACLXOFNAJPuQYWdBoVhQ==,type:str]
        securityContext:
            privileged: true
        dind:
            resources:
                requests:
                    cpu: 50m
                    memory: 1Gi
                limits:
                    memory: 2Gi
        resources:
            requests:
                cpu: 50m
                memory: 128Mi
            limits:
                memory: 256Mi
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQeXpvVGd1NTgxa2xua3ZN
            VHNiNFJnUFZYdlowWWlzK3Fkb05OeXYvSzNzCkRMcXhPY3l1cEpvc2xEL3NlNjZX
            eEtXdjBWcDd5VGtUYVk1ektsSm1GcGMKLS0tIDBFWFc3emJwbEhhdy9Gc2ZEWnBH
            cG9OYUFKMEdHNHhHcWV3T0tvWlViMTQK0dPq+VX/Ny6NlVIQ/IJTgQmh+pZvyjFG
            jD0qncBeAT9g6iE4RucltmGqWI5Vqx59qraPwPcaDjLbUeCp1ym1uA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1luplm36pk0f4j5835tygt6wuqfjqe7ra6u8w0t86xrhhprycgfysjjmgux
    encrypted_regex: ^(token|uuid)$
    lastmodified: "2026-06-26T11:17:38Z"
    mac: ENC[AES256_GCM,data:GLR62wzTMkw6oP80ADzVqPmgUOGD65YBaZ641l4ixt+CW/ai3cbY2gQZ3xfIc+mqiCdQ/d97ygQ99opndLrAKDK6n8Mxrt2lpnmArP10jHvG8I5GLM4gkQlZ/AkFkyyYtFYr1/ZcDmHvaGtDBE+5NlpvHD8p5S3Ko8NWNZgiLIk=,iv:I28juZoD/oBFYUnBtYyPupkEPs1/JwYRxRRA2eZs/2U=,tag:HeNjXphbDhpz03252FrJbQ==,type:str]
    version: 3.13.1
