apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-server
    namespace: forgejo-runner
type: Opaque
stringData:
    FORGEJO_URL: http://forgejo-http.forgejo.svc.cluster.local:3000
    FORGEJO_UUID: ENC[AES256_GCM,data:8pmL6I2eO7NdFwuyIoJEtSfytsLk08t9yNpcYF53d3IBikqM,iv:NoHU2T+tIt+8N5Tg3RKYyCK0JI53gCf0n3d1Pj1fqvU=,tag:s2aZ/SJurxOLp7Tm+OGDTw==,type:str]
    FORGEJO_TOKEN: ENC[AES256_GCM,data:UJ+RVwHzjlRXvBWK+8CmZ6y6Bk7ywgttgSpBVlxV8ehPAAfUoxJwgg==,iv:dbdwAHPgAmRIJ72cEozYqeV/G0WzZJMAQ4FxOzH1cbo=,tag:CzOvbN4Fi5WEMSOIo0WDkA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1aDQ0QUc2QXJsU1RvTGtN
            bE5KQ1dPaTRHOU4wUmcvVXBubGdiVUh2UGswClowTDBMNmt4RVVxUldyVmY5Qlkw
            VWVFNmZPNHRYWHYrQ1o4T1hQRlhwaGsKLS0tIHQ5QUk3dW5QejRoSU0wejZDME1a
            SzhoWEVZSHJBNm82LzNuMHhQNGdoMXMKLozVIHg+ifKmPK7+xofgmlY/8Lo16l4Z
            kvPXvr/DjXG7q4LaW/YeRkZ4HN+naGOj5aFOVYOPx1rjRuibFFGN1g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1luplm36pk0f4j5835tygt6wuqfjqe7ra6u8w0t86xrhhprycgfysjjmgux
    encrypted_regex: ^(FORGEJO_UUID|FORGEJO_TOKEN)$
    lastmodified: "2026-07-03T13:27:23Z"
    mac: ENC[AES256_GCM,data:v9xisuLssw9dR1CeQ44xA61ec6eDe4rooyQGZQY5KfNm9YC6s2owoorwE0HplGfosFh2JkNTfYZHDiHVy7GhRjyuoj18epOgAJ0U+gIdrm5A+zDw5w7hwJsAkSu/K8VvwMOIOy5lubIXRTtWnMeEv6WF7CzUUYk6u0dZz60+YxU=,iv:CDjQijxHPjFbb7k7brCGu9/YTCFXMrI7pNAICRn6r5U=,tag:GQgTXNFgpOLaa1CnrIQ3SQ==,type:str]
    version: 3.13.1
