apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-server
    namespace: forgejo-runner
type: Opaque
stringData:
    FORGEJO_URL: http://forgejo-http.forgejo.svc.cluster.local:3000
    FORGEJO_UUID: ENC[AES256_GCM,data:TSXO6ShJYGsYW1E3sdrVPKIpYwrRlK3wx+YbimPpmGukJ0Bl,iv:1kGv4oNXjI9EmYcdfITS1A8z2vEvrzlBejKL/SjXfW0=,tag:Leyq1+XGx8N3Q/aCUXMvUw==,type:str]
    FORGEJO_TOKEN: ENC[AES256_GCM,data:6mJVf7feGdO2SmQQT7yW8Ecczi5H37/8X3d+eaKG8a4ejCp3sMb+cw==,iv:/8GbOaE0V/0UojDBAuk1KRUaY+b9v3Odq58UB7Ho/GY=,tag:rLSdZUBEiOYE0xMCj5f90g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZS80eEZrSm4wNHlYQ2VU
            dGdha2pvM0EvR05SOUJBSGZZYUM4OVYrVVNnCmwzdDdQRjBBY2d0NERGMkh4NXFU
            RUw4NUVQQXp3R0JDUVVzVzAzRURnK0UKLS0tIHkwd21MK3RUcVF6YzdzdXlHUitZ
            ZXdNcXZ0cUtIY1QyYW05a043UkE0eWcKeoQycmJsK4THo46ASPDNkbO/hoR2zOpw
            uC49dtwVWKIOo+E6vcEbEA+mwObwwE84O56lO7JGWtpKcnFVe1UYzw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1luplm36pk0f4j5835tygt6wuqfjqe7ra6u8w0t86xrhhprycgfysjjmgux
    encrypted_regex: ^(FORGEJO_UUID|FORGEJO_TOKEN)$
    lastmodified: "2026-06-26T11:20:09Z"
    mac: ENC[AES256_GCM,data:rU5gBz+armUizwF1FANQXkbDWhPc66bEQwuf1Pl7OQPJ39hRGFuvK2N4YiX3ilwTOWlb2uGdNsd79suqvNNtrKV41o86LqbAe6q3ieTHouhr11q2CMPIMRuSRMBIbrKtxbquklpcnNbZNSo1WtA0Y3vTel3kq64zof+Uj5wRqrw=,iv:nw90a+3C8fLjMYS9cl3lC6n6bnl9nkm6d6auSY/+AYI=,tag:hH6QI6aivuPePzT5BZMiHQ==,type:str]
    version: 3.13.1
