apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-config
    namespace: forgejo-runner
type: Opaque
stringData:
    .runner: ENC[AES256_GCM,data:1oTDA0vzEyMMf1cYgyM8DQW+biuBuxaZrZhzv17JN+RWPLfx7B+/IHFR9P35T1kBYkfxm3tm1/Mtfs7/TIAiKlWMKkitzh4sOSVYUbaKc2tBKu/XVHm0vvQQRyukhD4RJZ5j65I5TEHIwlU4+CkWAT3lOrc2jqtDA4nKs7x9xy+SuNBqPinBx3onL7QkbuyoOGXz7Dyi3jr5vPsIbIJQZbvWf5TIsAcQL3Gaw5L+sg==,iv:Crw8cSzO9T7a/BlYhg7U8O0HD5HjBrPXM06D95GqvxY=,tag:UjxegoAbghK84cbGyQ6+BA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORXJ4dXg5N2t0aitFVnIr
            V0g4Mk4wajBjWVRxU0U1cERRZDN0L2wzTVVNCitOSkRsYWZicjczb05tbllGbURL
            bVRFV015V0ROd2I1bzJBUm1YTDdNT1UKLS0tIGxmSkNFcXoydDNhbEVXOXl4cHoy
            ZGVhZmFaWGVJQXE5c2FWbVNNd29LRVUKgI3/KFh2Lk/0PjChjgk7LN6hKomCFw8F
            P6LPdUYnnn+52ElkGQYyISbhnEna33cf2XyU+lfU9iTcMK3nM4919A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1luplm36pk0f4j5835tygt6wuqfjqe7ra6u8w0t86xrhhprycgfysjjmgux
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-26T10:57:49Z"
    mac: ENC[AES256_GCM,data:g461Frrt9BYXVOQUIokkQHH1jVNLXIhAlX0ycmFfy1hfV8IgVkomVhpcMjiJU2fjcwVyEZ3euGXGfsGMCFYMtR4bENZGO+KNh/BDLblKb+OksLz6gd3bol463nrLg19vrr07JNB/rG7tCXbEx3zxynZiwnGpyTWpXc5EGR7U2i8=,iv:DK40B50sNSXY1FnLeZptjI+FzuwIKYGleG1u4q/2DDk=,tag:F7sH69az9XraQbYx44iV1A==,type:str]
    version: 3.13.1
